apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e3g96litk-nodejs
  janus-idp.io/tekton: e3g96litk-nodejs
  backstage.io/kubernetes-id: e3g96litk-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e3g96litk-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
